zuul:
  routes:
    employee:
      path: /employee/**
      serviceId: EMPLOYEESERVICE
    department:
      path: /department/**
      serviceId: DEPARTMENTSERVICE
server:
  port: 8091
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8020/eureka
    register-with-eureka: true
    fetchRegistry: true
  instance:
    prefer-ip-address: false
spring:
  application:
    name: ZuulGatewayService
    
    
   