zuul:
  routes:
    employee:
      serviceId: EMPLOYEESERVICES
    department:
      serviceId: DEPARTMENT

ribbon:
  eureka:
    enabled: false

EMPLOYEESERVICES:
  ribbon:
    eureka:
      enabled: false
    listOfServers: http://localhost:8092,http://localhost:8094

DEPARTMENT:
  ribbon:
    eureka:
      enabled: false
    listOfServers: http://localhost:8093,http://localhost:8095

server:
  port: 8091
spring:
  application:
    name: ZuulGatewayService
    
    
   